//simple Java program
/*
  java is case sensitive, must have a main method
  classes in the standard java library are accessed using Java API

  variables vs literals

  variable- memory address
  literal- value written into code

  + operator
  -concatenation of strings
  -adds numbers, integers and floats

  string literal value cannot span lines in a Java source code file.

  System.out,printLn("This line is too long and now it has spanned more than one line, which will cause a syntax error to be generated by the compiler.");

  vs

  System.out,printLn("This line is too long" +  "and now it has spanned more than 
  one line," +  "which will cause a syntax error to be generated by the compiler.");

  identifiers are programmer-defined names for classes, variables, methods
  identifiers cannot include reserved keywords

  Variables names allow code to be more readable; therefore, the code is more maintainable.

  primitive datatypes: byte short int long float double char (pronounced care) boolean

  1 byte 
  byte

  2 bytes
  short

  4 bytes
  int float

  8 bytes
  long double

  java is strongly typed, meaning you cant change the type of a value within a variable. 

  final 
  final is used to create consts; 
  final int CAL_SALES_TAX = 0.725
  or
  final int cal_sales_tax = 0.725

  java had no primitive datatype to hold strings
  java uses a String class
  String Number;

  Objects are not stored in variables, however objects are referenced by variables.



*/

//class header
public class Simple {
  //method header
  //Java programs must have a main method
  public static void main(String[] args) {
    //Java statement
    //only Java statements end with ;
    System.out.printLn("Programming is great fun!");
    System.out.printLn("We can join a string to " + "a number line this: " + (5 + 3));
  }
}